name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Klonowanie repozytorium
      - name: Checkout code
        uses: actions/checkout@v3

      # Logowanie do Docker Hub lub GHCR
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Budowanie obrazu Dockera
      - name: Build Docker image
        run: |
          docker build -t my-app:latest .
          docker tag my-app:latest USERNAME/my-app:latest

      # Wysyłanie obrazu do rejestru
      - name: Push Docker image
        run: |
          docker push USERNAME/my-app:latest
